name: riverpod_lint_unknown_provider
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.2

dependencies:
  riverbloc: ^2.2.0
  riverpod: ^2.4.0

dev_dependencies:
  custom_lint: ^0.5.3
  lints: ^2.0.0
  riverpod_lint: ^2.1.0
